### ISSUE TITLE
Need to add metrics and unit tests

### ISSUE THREAD

**Issue by dak1n1** [openshift/configure-alertmanager-operator#1]
Configure-alertmanager-operator is lacking some minimum requirements. This issue will track metrics and unit tests.

**Comment by jewzaam** [comment]
Recommend splitting metrics out, relative to other issues it's lower priority.

**Comment by fahlmant** [comment]
It's fairly simple to add metrics. @dak1n1 Here's a simple example: https://github.com/openshift/certman-operator/blob/master/pkg/metrics/metrics.go

**Comment by dak1n1** [comment]
PR is ready for review at https://github.com/openshift/configure-alertmanager-operator/pull/14
