### ISSUE TITLE
RFE: make timestamps more readable

### ISSUE THREAD

**Issue by dak1n1** [openshift/configure-alertmanager-operator#4]
The timestamps on our current logging implementation are difficult to read. Let's see if we can get them into UTC with an easy-to-read format like `2019-04-17T18:30:00`.

https://gist.githubusercontent.com/dak1n1/24a90c2ce8cfcd5f90021d05c8d70dca/raw/6027eb5ceab698557ac00e39e3aad53fe39878ef/gistfile1.txt

**Comment by jewzaam** [comment]
I like the format proposed.  If we can I'd add milliseconds.  Also be clear on timezone.  Prefer default timezone to whatever the system timezone is, but open explicitly setting to UTC for consistency.

**Comment by fahlmant** [comment]
Assuming that all of the machines we are managing will be on UTC, I vote we go with UTC.

**Comment by jewzaam** [comment]
Looks like they are, but I don't think we can rely on something like that
to be consistent over time simply because we don't have control.  So would
say we force it to UTC and be done.

```
$ oc rsh -n openshift-dedicated-admin $(oc get pods -n
openshift-dedicated-admin | tail -n1 | awk '{print $1}') date
Thu Apr 18 14:51:30 UTC 2019
```
