### ISSUE TITLE
Specifying routes for additional alerts

### ISSUE THREAD

**Issue by usamaahmadkhan** [openshift/configure-alertmanager-operator#87]
I'm using pagerduty-operator with this and the alertmanager config generates nicely in `alertmanager-main` secret. but there are 2 use cases I have:

1. Sending alerts to pagerduty that are sent to `null` by default. How to send this to pagerduty as well.
```
    - receiver: "null"
      match:
        alertname: KubeQuotaExceeded
```
2. Adding additional routes for some other alerts. How can this be achieved?

**Comment by jewzaam** [comment]
Create a secret in openshift-monitoring called pd-secret with the API key for the PD service in "PAGERDUTY_KEY".  This operator picks up that secret and configures alertmanager routing rules.  There is work in progress to put this into a CRD: https://github.com/openshift/configure-alertmanager-operator/pull/78

**Comment by usamaahmadkhan** [comment]
@jewzaam since #78 is closed. Need your suggestion on satisfying my following use case:

I have an alert `ExampleAlertFromExampleNamespace` in my alertmanager generated from my app namespace `example-namespace`. This Alert is not being forwarded to pagerduty since the operator is focusing/forwarding for default or openshift namespaces:
https://github.com/openshift/configure-alertmanager-operator/blob/a1a1055e5c6b053ec6075bef82bd507a28d78632/pkg/types/alertmanagerconfig.go#L14

Is there a way to achieve this? I don't want to put `openshift-` prefix in my app namespace name.
