### ISSUE TITLE
Regex needs tweaked

### ISSUE THREAD

**Issue by jewzaam** [openshift/configure-alertmanager-operator#9]
Regex https://github.com/openshift/configure-alertmanager-operator/blob/6ed52de8ca02ca7a0e845160f8c08d015d5474d3/pkg/controller/secret/secret_controller.go#L256

should be probably be aligned with https://github.com/openshift/dedicated-admin-operator/blob/4e291032ae834f9397ecfa7a8a216c8c79050bbd/pkg/dedicatedadmin/dedicatedadmin.go#L53

**Comment by dak1n1** [comment]
Done in https://github.com/openshift/configure-alertmanager-operator/pull/18
